---
cloud_controller_uri: http://api.vcap.me # NB: make sure this is uncommented and the DNS name resolves (hosts file, for instance)

service:
  name: mssql
  version: "10.50.2500"
  description: 'MS SQL database service'
  plans: ['free']
  tags: ['mssql', 'SQL Server 2008 R2', 'relational']

ip_route: 172.21.10.231 # localhost

#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true

index: 0

token: "0xdeadbeef"

logging:
  level: debug
  file: C:/CloudFoundry/log/mssql_gateway.log

mbus: nats://172.21.193.11:4222

pid: C:/CloudFoundry/vcap/sys/run/mssql_service.pid

node_timeout: 2

# allow_over_provisioning: false
