---
local_db: sqlite3:C:/CloudFoundry/vcap/services/mssql/mssql_node.db

base_dir: C:/CloudFoundry/vcap/services/mssql/

sqlcmd_bin: 'C:/Program Files/Microsoft SQL Server/100/Tools/Binn/sqlcmd.exe'

ip_route: 172.21.10.231

mbus: nats://172.21.193.11:4222

index: 0

logging:
  level: debug
  file: C:/CloudFoundry/log/mssql_node.log

pid: C:/CloudFoundry/vcap/sys/run/mssql_node.pid

available_storage: 1024

node_id: mssql_node_1

max_db_size: 20
max_long_query: 3
max_long_tx: 30

migration_nfs: C:/CloudFoundry/mnt/migration

# To specify port, use IP,PORT in 'host' - 192.168.1.1,1433
mssql:
  host: 172.21.10.231,1433
  user: sa
  pass: password1
