# Services we provide, and their tokens. Avoids bootstrapping DB.
builtin_services:
  mysql:
    token: "0xdeadbeef"
  mssql:
    token: "0xdeadbeef"
  postgresql:
    token: "0xdeadbeef"
  redis:
    token: "0xdeadbeef"
  mongodb:
    token: "0xdeadbeef"
  rabbitmq:
    token: "0xdeadbeef"

# used for /info/runtimes endpoint (served unfiltered as JSON)
runtimes:
  aspdotnet40:
    version: 4.0.30319.0
  ruby18:
    version: 1.8.7
  ruby19:
    version: 1.9.2
  node:
    version: 0.4.[2-9]
  java:
    version: 1.6.0
    debug_modes:
      - run
      - wait
  php:
    version: 5.3.[2-6]
  erlangR14B02:
    version: ".* 5.8.3"
  python26:
    version: 2.6.5
